{"cells":[{"cell_type":"code","execution_count":2,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"AI4s6nxW2TmC","executionInfo":{"status":"ok","timestamp":1676645355906,"user_tz":-540,"elapsed":3508,"user":{"displayName":"유승우","userId":"18267622456325964228"}},"outputId":"76c5772f-d92d-42bf-9dd0-097810e8badc"},"outputs":[{"output_type":"stream","name":"stdout","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"]}],"source":["from google.colab import drive\n","\n","drive.mount('/content/drive')\n","\n","# TODO: Enter the path in your Drive of the assignment.\n","# e.g. 'cs231n/assignments/assignment2/'\n","FOLDERNAME = 'cs231n/assignments/assignment2/'\n","\n","assert FOLDERNAME is not None, \"[!] Enter the foldername.\""]},{"cell_type":"markdown","metadata":{"id":"RCkwfEMP2TmD"},"source":["# Collect Submission - Zip + Generate PDF \n","\n","Run this notebook once you have completed all the other notebooks: `FullyConnectedNets.ipynb`, `BatchNormalization.ipynb`, `Dropout.ipynb`, `ConvolutionalNetworks.ipynb`, `TensorFlow/PyTorch.ipynb`, `Network_Visualization.ipynb`).\n","\n","It will:\n","\n","* Generate a zip file of your code (`.py` and `.ipynb`) called `a2_code_submission.zip`.\n","* Convert all notebooks into a single PDF file called `a2_inline_submission.pdf`.\n","\n","If your submission for this step was successful, you should see the following display message:\n","\n","`### Done! Please submit a2_code_submission.zip and the a2_inline_submission.pdf to Gradescope. ###`\n","\n","Make sure to download the zip and pdf file locally to your computer, then submit to Gradescope. Congrats on succesfully completing the assignment!"]},{"cell_type":"code","execution_count":3,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"kMLeiDeA2TmN","executionInfo":{"status":"ok","timestamp":1676645393514,"user_tz":-540,"elapsed":34098,"user":{"displayName":"유승우","userId":"18267622456325964228"}},"outputId":"ca90d60c-e500-4a94-e1b3-97e8c1de265e"},"outputs":[{"output_type":"stream","name":"stdout","text":["/content/drive/My Drive/cs231n/assignments/assignment2\n","Get:1 https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease [3,622 B]\n","Ign:2 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64  InRelease\n","Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease\n","Hit:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64  Release\n","Get:5 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]\n","Hit:6 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu focal InRelease\n","Hit:7 http://archive.ubuntu.com/ubuntu focal InRelease\n","Get:9 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]\n","Hit:10 http://ppa.launchpad.net/cran/libgit2/ubuntu focal InRelease\n","Get:11 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2,496 kB]\n","Hit:12 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease\n","Hit:13 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal InRelease\n","Get:14 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]\n","Get:15 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [998 kB]\n","Get:16 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [1,937 kB]\n","Hit:17 http://ppa.launchpad.net/ubuntugis/ppa/ubuntu focal InRelease\n","Get:18 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2,970 kB]\n","Get:19 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1,297 kB]\n","Fetched 10.0 MB in 2s (4,163 kB/s)\n","Reading package lists... Done\n","Reading package lists... Done\n","Building dependency tree       \n","Reading state information... Done\n","E: Unable to locate package texlive-generic-recommended\n","Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n","Collecting PyPDF2\n","  Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m232.6/232.6 KB\u001b[0m \u001b[31m8.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hRequirement already satisfied: typing_extensions>=3.10.0.0 in /usr/local/lib/python3.8/dist-packages (from PyPDF2) (4.4.0)\n","Installing collected packages: PyPDF2\n","Successfully installed PyPDF2-3.0.1\n","### Zipping file ###\n","### Creating PDFs ###\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/jupyter-nbconvert\", line 8, in <module>\n","    sys.exit(main())\n","  File \"/usr/local/lib/python3.8/dist-packages/jupyter_core/application.py\", line 277, in launch_instance\n","    return super().launch_instance(argv=argv, **kwargs)\n","  File \"/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n","    app.start()\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 340, in start\n","    self.convert_notebooks()\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 510, in convert_notebooks\n","    self.convert_single_notebook(notebook_filename)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 481, in convert_single_notebook\n","    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 410, in export_single_notebook\n","    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/exporter.py\", line 179, in from_filename\n","    return self.from_file(f, resources=resources, **kw)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/exporter.py\", line 197, in from_file\n","    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/pdf.py\", line 185, in from_notebook_node\n","    self.run_latex(tex_file)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/pdf.py\", line 155, in run_latex\n","    return self.run_command(self.latex_command, filename,\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/pdf.py\", line 112, in run_command\n","    raise OSError(\"{formatter} not found on PATH, if you have not installed \"\n","OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n","Created PDF FullyConnectedNets.ipynb.\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/jupyter-nbconvert\", line 8, in <module>\n","    sys.exit(main())\n","  File \"/usr/local/lib/python3.8/dist-packages/jupyter_core/application.py\", line 277, in launch_instance\n","    return super().launch_instance(argv=argv, **kwargs)\n","  File \"/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n","    app.start()\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 340, in start\n","    self.convert_notebooks()\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 510, in convert_notebooks\n","    self.convert_single_notebook(notebook_filename)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 481, in convert_single_notebook\n","    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 410, in export_single_notebook\n","    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/exporter.py\", line 179, in from_filename\n","    return self.from_file(f, resources=resources, **kw)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/exporter.py\", line 197, in from_file\n","    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/pdf.py\", line 185, in from_notebook_node\n","    self.run_latex(tex_file)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/pdf.py\", line 155, in run_latex\n","    return self.run_command(self.latex_command, filename,\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/pdf.py\", line 112, in run_command\n","    raise OSError(\"{formatter} not found on PATH, if you have not installed \"\n","OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n","Created PDF BatchNormalization.ipynb.\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/jupyter-nbconvert\", line 8, in <module>\n","    sys.exit(main())\n","  File \"/usr/local/lib/python3.8/dist-packages/jupyter_core/application.py\", line 277, in launch_instance\n","    return super().launch_instance(argv=argv, **kwargs)\n","  File \"/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n","    app.start()\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 340, in start\n","    self.convert_notebooks()\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 510, in convert_notebooks\n","    self.convert_single_notebook(notebook_filename)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 481, in convert_single_notebook\n","    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 410, in export_single_notebook\n","    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/exporter.py\", line 179, in from_filename\n","    return self.from_file(f, resources=resources, **kw)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/exporter.py\", line 197, in from_file\n","    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/pdf.py\", line 185, in from_notebook_node\n","    self.run_latex(tex_file)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/pdf.py\", line 155, in run_latex\n","    return self.run_command(self.latex_command, filename,\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/pdf.py\", line 112, in run_command\n","    raise OSError(\"{formatter} not found on PATH, if you have not installed \"\n","OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n","Created PDF Dropout.ipynb.\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/jupyter-nbconvert\", line 8, in <module>\n","    sys.exit(main())\n","  File \"/usr/local/lib/python3.8/dist-packages/jupyter_core/application.py\", line 277, in launch_instance\n","    return super().launch_instance(argv=argv, **kwargs)\n","  File \"/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n","    app.start()\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 340, in start\n","    self.convert_notebooks()\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 510, in convert_notebooks\n","    self.convert_single_notebook(notebook_filename)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 481, in convert_single_notebook\n","    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 410, in export_single_notebook\n","    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/exporter.py\", line 179, in from_filename\n","    return self.from_file(f, resources=resources, **kw)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/exporter.py\", line 197, in from_file\n","    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/pdf.py\", line 185, in from_notebook_node\n","    self.run_latex(tex_file)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/pdf.py\", line 155, in run_latex\n","    return self.run_command(self.latex_command, filename,\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/pdf.py\", line 112, in run_command\n","    raise OSError(\"{formatter} not found on PATH, if you have not installed \"\n","OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n","Created PDF ConvolutionalNetworks.ipynb.\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/jupyter-nbconvert\", line 8, in <module>\n","    sys.exit(main())\n","  File \"/usr/local/lib/python3.8/dist-packages/jupyter_core/application.py\", line 277, in launch_instance\n","    return super().launch_instance(argv=argv, **kwargs)\n","  File \"/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n","    app.start()\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 340, in start\n","    self.convert_notebooks()\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 510, in convert_notebooks\n","    self.convert_single_notebook(notebook_filename)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 481, in convert_single_notebook\n","    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 410, in export_single_notebook\n","    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/exporter.py\", line 179, in from_filename\n","    return self.from_file(f, resources=resources, **kw)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/exporter.py\", line 197, in from_file\n","    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/pdf.py\", line 185, in from_notebook_node\n","    self.run_latex(tex_file)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/pdf.py\", line 155, in run_latex\n","    return self.run_command(self.latex_command, filename,\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/pdf.py\", line 112, in run_command\n","    raise OSError(\"{formatter} not found on PATH, if you have not installed \"\n","OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n","Created PDF PyTorch.ipynb.\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/jupyter-nbconvert\", line 8, in <module>\n","    sys.exit(main())\n","  File \"/usr/local/lib/python3.8/dist-packages/jupyter_core/application.py\", line 277, in launch_instance\n","    return super().launch_instance(argv=argv, **kwargs)\n","  File \"/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n","    app.start()\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 340, in start\n","    self.convert_notebooks()\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 510, in convert_notebooks\n","    self.convert_single_notebook(notebook_filename)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 481, in convert_single_notebook\n","    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py\", line 410, in export_single_notebook\n","    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/exporter.py\", line 179, in from_filename\n","    return self.from_file(f, resources=resources, **kw)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/exporter.py\", line 197, in from_file\n","    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/pdf.py\", line 185, in from_notebook_node\n","    self.run_latex(tex_file)\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/pdf.py\", line 155, in run_latex\n","    return self.run_command(self.latex_command, filename,\n","  File \"/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/pdf.py\", line 112, in run_command\n","    raise OSError(\"{formatter} not found on PATH, if you have not installed \"\n","OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n","Created PDF Network_Visualization.ipynb.\n","Traceback (most recent call last):\n","  File \"makepdf.py\", line 45, in <module>\n","    main(args.notebooks, args.pdf_filename)\n","  File \"makepdf.py\", line 29, in main\n","    merger = PdfFileMerger()\n","  File \"/usr/local/lib/python3.8/dist-packages/PyPDF2/_merger.py\", line 817, in __init__\n","    deprecation_with_replacement(\"PdfFileMerger\", \"PdfMerger\", \"3.0.0\")\n","  File \"/usr/local/lib/python3.8/dist-packages/PyPDF2/_utils.py\", line 369, in deprecation_with_replacement\n","    deprecation(DEPR_MSG_HAPPENED.format(old_name, removed_in, new_name))\n","  File \"/usr/local/lib/python3.8/dist-packages/PyPDF2/_utils.py\", line 351, in deprecation\n","    raise DeprecationError(msg)\n","PyPDF2.errors.DeprecationError: PdfFileMerger is deprecated and was removed in PyPDF2 3.0.0. Use PdfMerger instead.\n"]}],"source":["%cd drive/My\\ Drive/$FOLDERNAME\n","!sudo apt-get update\n","!sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-generic-recommended\n","!pip install PyPDF2\n","!bash collectSubmission.sh"]}],"metadata":{"colab":{"provenance":[]},"language_info":{"name":"python"},"kernelspec":{"name":"python3","display_name":"Python 3"},"gpuClass":"standard"},"nbformat":4,"nbformat_minor":0}